#### general settings
name: cingan
use_tb_logger: false
model: CinGANModel
scale: 4
gpu_ids: [5]
metrics: [psnr, ssim]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: PairedRefDataset
    data_type: lmdb
    color: RGB
    ratios: [1, 4]

    dataroot_ref_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2020/train_target.lmdb
    dataroot_ref_src: /mnt/hdd/lzx/SRDatasets/NTIRE2020/BicLRx4.lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2020/track1/track1_train_source.lmdb

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 32
    tgt_size: 128
    src_size: 32
    use_flip: true
    use_rot: true

 val:
    name: 2020Track1_mini
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2020/track1/valid_mini.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/DIV2K_valid/HR/x4_mini.lmdb
    
#### network structures
netSR:
  which_network: EDSR
  setting:
    nf: 64
    nb: 16
    res_scale: 0.1
    upscale: 4
  pretrain: 
    path: ../../../checkpoints/EDSR/edsr_baseline_x4-6b446fab.pt
    strict_load: true

netD2:
  which_network: PatchGANDiscriminator
  setting:
    in_c: 3
    nf: 64
    nb: 3
    stride: 1
  
#### network structures  
netG1:
  which_network: Translator
  setting:
    nf: 64
    nb: 8
    scale: 1
  pretrain: 
    path: log/cyclegan_translation/models/latest_netG1.pth
    strict_load: true

netD1:
  which_network: PatchGANDiscriminator
  setting:
    in_c: 3
    nf: 64
    nb: 3
    stride: 1
  pretrain: 
    path: log/cyclegan_translation/models/latest_netD1.pth
    strict_load: true

netG2:
  which_network: Translator
  setting:
    nf: 64
    nb: 8
    scale: 1
  pretrain: 
    path: log/cyclegan_translation/models/latest_netG2.pth
    strict_load: true

netG3:
  which_network: Translator
  setting:
    nf: 64
    nb: 8
    scale: 0.25
  pretrain: 
    path: ~
    strict_load: true


#### training settings: learning rate scheme, loss
train:
  resume_state: ~

  losses:
    srd2_adv:
      type: GANLoss
      gan_type: vanilla
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 0.5
    
    sr_tv:
      type: TVLoss
      penealty: MSELoss
      weight: 0.2

    srg3_cycle:
      type: L1Loss
      weight: 1

    g1d1_adv:
      type: GANLoss
      gan_type: vanilla
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 0.1
    
    lr_tv:
      type: TVLoss
      penealty: MSELoss
      weight: 0.05
    
    g1g2_cycle:
      type: L1Loss
      weight: 1.0

  optimizers:
    netSR:
      type: Adam
      lr: !!float 1e-4
    netG1:
      type: Adam
      lr: !!float 1e-4
    netG2:
      type: Adam
      lr: !!float 1e-4
    netD1:
      type: Adam
      lr: !!float 1e-4
    netD2:
      type: Adam
      lr: !!float 1e-4
    netG3:
      type: Adam
      lr: !!float 1e-4
  
  niter: 100000
  warmup_iter: -1  # no warm up

  scheduler:
    type: MultiStepLR
    milestones: [50000]
    gamma: 0.5

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
