#### general settings
name: cyclegan_translation
use_tb_logger: false
model: CycleGANModel
scale: 1
gpu_ids: [3]
metrics: [psnr, ssim]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: UnPairedDataset
    data_type: lmdb
    color: RGB
    ratio: 8

    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2020/BicLRx4_half.lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2017/trainx4_half.lmdb

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 32
    tgt_size: 32
    src_size: 32
    use_flip: true
    use_rot: true

  val:
    name: DIV2K
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/DIV2K_valid/BicLR/x4.lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2017/validx4.lmdb

#### network structures  
netG1:
  which_network: Translator
  setting:
    nf: 64
    nb: 8
    zero_tail: true
    scale: 1
  pretrain: 
    path: ~
    strict_load: true

netD1:
  which_network: PatchGANDiscriminator
  setting:
    in_c: 3
    nf: 64
    nb: 3
    stride: 1

netG2:
  which_network: Translator
  setting:
    nf: 64
    nb: 8
    zero_tail: true
    scale: 1
  pretrain: 
    path: ~
    strict_load: true

#### training settings: learning rate scheme, loss
train:
  resume_state: ~

  losses:
    g1d1_adv:
      type: GANLoss
      gan_type: vanilla
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 0.5

    g1g2_cycle:
      type: L1Loss
      weight: 1.0
      
    lr_tv:
      type: TVLoss
      weight: 0.05

  optimizers:
    netG1:
      type: Adam
      lr: !!float 1e-4
    netG2:
      type: Adam
      lr: !!float 1e-4
    netD1:
      type: Adam
      lr: !!float 1e-4
    netD2:
      type: Adam
      lr: !!float 1e-4
  
  niter: 100000
  warmup_iter: -1  # no warm up

  scheduler:
    type: MultiStepLR
    milestones: [50000]
    gamma: 0.5

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
