#### general settings
name: cggan
use_tb_logger: false
model: CGGANModel
scale: 4
gpu_ids: [2]
metrics: [psnr, ssim]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: PairedRefDataset
    data_type: lmdb
    color: RGB
    ratios: [4, 1]

    dataroot_ref_tgt: /mnt/raid/lzx/SRDatasets/DIV2K_train/HR/x4_half.lmdb
    dataroot_ref_src: /mnt/raid/lzx/SRDatasets/DIV2K_train/BicLR/x4_half.lmdb
    dataroot_src: /mnt/raid/lzx/SRDatasets/NTIRE2017/train_LR/x4_half.lmdb

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 8
    tgt_size: 480
    src_size: 120
    use_flip: true
    use_rot: true

  val:
    name: 2017Track1_mini
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_src: /mnt/raid/lzx/SRDatasets/NTIRE2017/valid_LR/x4_mini.lmdb
    dataroot_tgt: /mnt/raid/lzx/SRDatasets/DIV2K_valid/HR/x4_mini.lmdb

#### network structures
netSR:
  which_network: EDSR
  setting:
    nf: 64
    nb: 16
    res_scale: 0.1
    upscale: 4
  pretrain: 
    path: ../../../checkpoints/EDSR/edsr_baseline_x4-6b446fab.pt
    strict_load: true

netD2:
  which_network: PatchGANDiscriminator
  setting:
    in_c: 3
    nf: 64
    nb: 3
    stride: 1
  
#### network structures  
netG1:
  which_network: Translator
  setting:
    nf: 64
    nb: 8
    zero_tail: true
    scale: 1
  pretrain: 
    path: ~
    strict_load: true

netD1:
  which_network: PatchGANDiscriminator
  setting:
    in_c: 3
    nf: 64
    nb: 3
    stride: 1
  pretrain: 
    path: ~
    strict_load: true

#### training settings: learning rate scheme, loss
train:
  resume_state: ~
  buffer_size: 12

  losses:
    sr_pix:
      type: L1Loss
      weight: 1

    srd2_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 1

    sr_tv:
      type: TVLoss
      penealty: L1Loss
      weight: 0.0
    
    sr_percep:
      type: PerceptualLoss
      layer_weights:
        'conv5_4': 1  # before relu
      vgg_type: vgg19
      use_input_norm: true
      range_norm: false
      perceptual_weight: 1.0
      style_weight: 0
      criterion: l1
      weight: !!float 0.0
    
    lr_percep:
      type: PerceptualLoss
      layer_weights:
        'conv5_4': 1  # before relu
      vgg_type: vgg19
      use_input_norm: true
      range_norm: false
      perceptual_weight: 1.0
      style_weight: 0
      criterion: l1
      weight: !!float 0.0

    g1d1_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 1.0

  optimizers:
    netSR:
      type: Adam
      lr: !!float 1e-4
    netG1:
      type: Adam
      lr: !!float 1e-4
    netD1:
      type: Adam
      lr: !!float 1e-4
    netD2:
      type: Adam
      lr: !!float 1e-4
  
  niter: 100000
  warmup_iter: -1  # no warm up

  scheduler:
    type: MultiStepLR
    milestones: [50000]
    gamma: 0.5

  manual_seed: 0
  val_freq: !!float 2.5e3

#### logger
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 5e3
