#### general settings
name: 2017Track1_ksize21_valid
use_tb_logger: false
model: LatenTransModel
scale: 4
gpu_ids: [4]
metrics: [psnr, ssim, lpips]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: UnPairedDataset
    data_type: lmdb
    color: RGB
    ratios: [800, 100]

    dataroot_tgt: /home/lzx/SRDatasets/DIV2K_train/HR/x4.lmdb
    dataroot_src: /home/lzx/SRDatasets/NTIRE2017/valid_LR/x4.lmdb

    use_shuffle: true
    workers_per_gpu: 4  # per GPU
    imgs_per_gpu: 32
    tgt_size: 128
    src_size: 32
    use_flip: true
    use_rot: true

  val:
    name: 2017Track1_mini
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_src: /home/lzx/SRDatasets/NTIRE2017/valid_LR/x4_mini.lmdb
    dataroot_tgt: /home/lzx/SRDatasets/DIV2K_valid/HR/x4_mini.lmdb

#### network structures
networks:
  Encoder:
    which_network: DegModel
    setting:
      scale: 4
      nc_img: 3
      kernel_opt: 
        mix: false
        spatial: false
        nc: 64
        nf: 64
        nb: 16
        body_k: 1
        head_k: 3
        ksize: 21
        zero_init: true
      noise_opt: ~
    pretrain: 
      path: log/2017Track1_ksize21_valid/models/125000_Encoder.pth
      strict_load: true

  Decoder:
    which_network: EDSR
    setting:
      nf: 64
      nb: 16
      res_scale: 1
      upscale: 4
    pretrain: 
      path: log/2017Track1_ksize21_valid/models/125000_Decoder.pth
      # path: ../../../checkpoints/EDSR/edsr_baseline_x4-new.pt
      strict_load: true

  netD1:
    which_network: PatchGANDiscriminator
    setting:
      in_c: 3
      nf: 64
      nb: 3
      stride: 1
    pretrain: 
      path: log/2017Track1_ksize21_valid/models/125000_netD1.pth
      strict_load: true

#### training settings: learning rate scheme, loss
train:
  resume_state: log/2017Track1_ksize21_valid/training_state/125000.state
  D_ratio: 1
  max_grad_norm: 50
  buffer_size: 0

  losses:
    sr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 0.0
    
    lr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 1.0
    
    lr_quant:
      type: L1Loss
      weight: 0.0

    sr_pix_trans: 
      type: L1Loss
      weight: 0.0
    
    sr_pix_sr: 
      type: L1Loss
      weight: 1.0

  optimizers:
    Encoder:
      type: Adam
      lr: !!float 2e-4
    Decoder:
      type: Adam
      lr: !!float 2e-4
    netD1:
      type: Adam
      lr: !!float 2e-4
   
  niter: 200000
  warmup_iter: -1  # no warm up

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 150000]
    gamma: 0.5

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  
