#### general settings
name: train2017_track2
use_tb_logger: false
model: SRModel
scale: 4
gpu_ids: [2]
metrics: [psnr, ssim]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2020/train_target.lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2017/trainx4.lmdb

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 32
    tgt_size: 128
    src_size: 32
    use_flip: true
    use_rot: true

  val:
    name: 2017track2
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2017/validx4_mini.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/DIV2K_valid/HR/x4_mini.lmdb

#### network structures
netSR:
  which_network: EDSR
  setting:
    nf: 64
    nb: 16
    res_scale: 1
    upscale: 4
  pretrain: 
    path: ~
    strict_load: true

#### training settings: learning rate scheme, loss
train:
  resume_state: ~

  losses:
    sr_pix: 
      type: L1Loss
      weight: 1.0

  optimizers:
    netSR:
      type: Adam
      lr: !!float 2e-4
    netD:
   
  niter: 400000
  warmup_iter: -1  # no warm up

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
