#### general settings
name: 2018Track2_psnr_v2
use_tb_logger: false
model: DegSRModel
scale: 4
gpu_ids: [0]
metrics: [best_psnr, best_ssim, lpips]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: UnPairedDataset
    data_type: lmdb
    color: RGB
    ratios: [200, 200]

    dataroot_tgt: /home/lzx/SRDatasets/DIV2K_train/HR/x4_half.lmdb
    dataroot_src: /home/lzx/SRDatasets/NTIRE2018/track2/x4_half.lmdb

    use_shuffle: true
    workers_per_gpu: 4  # per GPU
    imgs_per_gpu: 32
    tgt_size: 192
    src_size: 48
    use_flip: true
    use_rot: true

  val:
    name: 2018Track2
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_src: /home/lzx/SRDatasets/NTIRE2018/track2/valid_mini.lmdb
    dataroot_tgt: /home/lzx/SRDatasets/DIV2K_valid/HR/x4_mini.lmdb

#### network structures
networks:
  netDeg:
    which_network: DegModel
    setting:
      scale: 4
      nc_img: 3
      kernel_opt: 
        mix: false
        spatial: false
        nc: 64
        nf: 64
        nb: 16
        head_k: 1
        body_k: 1
        ksize: 21
        zero_init: true
      noise_opt: 
        mix: true
        nc: 3
        nf: 64
        nb: 16
        head_k: 3
        body_k: 3
        dim: 3
        zero_init: true
    pretrain: 
      path: ~
      strict_load: true

  netSR:
    which_network: EDSR
    setting:
      nf: 64
      nb: 16
      res_scale: 1
      upscale: 4
    pretrain: 
      path: ../../../checkpoints/EDSR/edsr_baseline_x4-new.pt
      strict_load: true

#### training settings: learning rate scheme, loss
train:
  resume_state: ~
  D_ratio: 1
  max_grad_norm: 50
  buffer_size: 0
  
  optim_deg: false
  optim_sr: true
  
  losses:
    sr_pix_sr: 
      type: L1Loss
      weight: 1.0
    
  optimizers:
    netSR:
      type: Adam
      lr: !!float 2e-4
   
  niter: 200000
  warmup_iter: -1  # no warm up

  schedulers:
    netSR:
      type: MultiStepLR
      milestones: [50000, 100000, 150000]
      gamma: 0.5

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
