#### general settings
name: 2020Track1_deg
use_tb_logger: false
model: DegSRModel
scale: 4
gpu_ids: [2]
metrics: [psnr, ssim, lpips]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: UnPairedDataset
    data_type: lmdb
    color: RGB
    ratios: [50, 200]

    dataroot_tgt: /home/lzx/SRDatasets/DIV2K_train/HR/x4.lmdb
    dataroot_src: /home/lzx/SRDatasets/NTIRE2020/track1/train_source.lmdb

    use_shuffle: true
    workers_per_gpu: 6  # per GPU
    imgs_per_gpu: 32
    tgt_size: 128
    src_size: 32
    use_flip: true
    use_rot: true

  val:
    name: 2020Track1
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_src: /home/lzx/SRDatasets/NTIRE2020/track1/valid_mini.lmdb
    dataroot_tgt: /home/lzx/SRDatasets/DIV2K_valid/HR/x4_mini.lmdb

#### network structures
networks:
  Encoder:
    which_network: Translator
    setting:
      nb: 16
      nf: 64
      scale: 0.25
      zero_tail: true
    pretrain: 
      # path: ~
      path: log/2020Track1/models/50000_Encoder.pth
      strict_load: true

  Decoder:
    which_network: EDSR
    setting:
      nf: 64
      nb: 16
      res_scale: 1
      upscale: 4
    pretrain: 
      path: ../../../checkpoints/EDSR/edsr_baseline_x4-new.pt
      strict_load: true

  netD1:
    which_network: PatchGANDiscriminator
    setting:
      in_c: 3
      nf: 64
      nb: 3
      stride: 1
    pretrain: 
      # path: ~
      path: log/2020Track1/models/50000_netD1.pth
      strict_load: true
  
#### training settings: learning rate scheme, loss
train:
  resume_state: log/2020Track1/training_state/50000.state
  D_ratio: 1
  max_grad_norm: 50
  buffer_size: 0

  losses:
    color: 
      type: ColorLoss
      ksize: 5
      stride: 4
      recursion: 1
      loss_type: mse
      weight: 1.0
    
    lr_percep:
      type: PerceptualLossLPIPS
      net: alex
      normalize: true
      weight: 0.01
    
    lr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 0.005
    
    sr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 0.0
    
    sr_pix_sr: 
      type: L1Loss
      weight: 1.0

  optimizers:
    Encoder:
      optim:
        type: Adam
        lr: !!float 2e-4
      scheduler:
        type: MultiStepLR
        milestones: [50000, 100000, 150000]
        gamma: 0.5
    Decoder:
      optim:
        type: Adam
        lr: !!float 2e-4
      scheduler:
        type: MultiStepLR
        milestones: [50000, 100000, 150000]
        gamma: 0.5
    netD1:
      optim:
        type: Adam
        lr: !!float 2e-4
      scheduler:
        type: MultiStepLR
        milestones: [50000, 100000, 150000]
        gamma: 0.5
   
  niter: 400000
  iter_split: 0.5
  warmup_iter: -1  # no warm up

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
