#### general settings
name: 2020Track1
use_tb_logger: false
model: CycleSRModel
scale: 4
gpu_ids: [0]

metrics: [psnr, ssim, lpips, niqe, piqe, brisque] 

datasets:
  # test1:
  #   name: 2017Track2
  #   mode: PairedDataset
  #   data_type: lmdb
  #   dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2017/validx4.lmdb
  #   dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2018/valid_HR.lmdb
  # test2:
  #   name: 2018Track2
  #   mode: PairedDataset
  #   data_type: lmdb
  #   dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2018/valid_mild.lmdb
  #   dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2018/valid_HR.lmdb
  # test3:
  #   name: 2018Track3
  #   mode: PairedDataset
  #   data_type: lmdb
  #   dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2018/valid_difficult.lmdb
  #   dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2018/valid_HR.lmdb
  # test4:
  #   name: 2018Track4
  #   mode: PairedDataset
  #   data_type: lmdb
  #   dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2018/valid_wild.lmdb
  #   dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2018/valid_HR.lmdb
  test5:
    name: 2020Track1
    mode: PairedDataset
    data_type: lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2020/track1/track1_valid_input.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2020/track1/track1_valid_gt.lmdb

#### network structures
Decoder:
  which_network: Decoder
  setting:
    nf: 64
    nb: 32
    scale_factor: 4
  pretrain: 
    path: log/2020Track1/models/5500_Decoder.pth
    strict_load: true