#### general settings
name: DegSpace
use_tb_logger: false
model: LatenTransModel
scale: 4
gpu_ids: [0]

metrics: [psnr, ssim, lpips, niqe, piqe, brisque] 

datasets:
  test1:
    name: 2017Track1
    mode: PairedDataset
    data_type: lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2017/valid_LR/x4.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/DIV2K_valid/HR/x4.lmdb
  # test2:
  #   name: 2018Track2
  #   mode: PairedDataset
  #   data_type: lmdb
  #   dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2018/valid_mild.lmdb
  #   dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2018/valid_HR.lmdb
  # test3:
  #   name: 2018Track3
  #   mode: PairedDataset
  #   data_type: lmdb
  #   dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2018/valid_difficult.lmdb
  #   dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2018/valid_HR.lmdb
  # test4:
  #   name: 2018Track4
  #   mode: PairedDataset
  #   data_type: lmdb
  #   dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2018/valid_wild.lmdb
  #   dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2018/valid_HR.lmdb
  # test5:
  #   name: 2020Track1
  #   mode: PairedDataset
  #   data_type: lmdb
  #   dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2020/track1_valid_input.lmdb
  #   dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2020/track1_valid_gt.lmdb

#### network structures
Decoder:
  which_network: EDSR
  setting:
    nf: 64
    nb: 16
    res_scale: 1
    upscale: 4
  pretrain: 
    path: log/2017Track1_10w/models/70000_Decoder.pth
    strict_load: true