#### general settings
name: 2020Track1
use_tb_logger: false
model: LatenTransModel
scale: 4
gpu_ids: [4]
metrics: [psnr, ssim]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: UnPairedDataset
    data_type: lmdb
    color: RGB
    ratios: [1, 4]

    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2020/train_target.lmdb
    # dataroot_ref_src: /mnt/hdd/lzx/SRDatasets/NTIRE2020/BicLRx4_half.lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2020/track1/track1_train_source.lmdb

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 32
    tgt_size: 128
    src_size: 32
    use_flip: true
    use_rot: true

  val:
    name: 2020Track1_mini
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2020/track1/valid_mini.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/DIV2K_valid/HR/x4_mini.lmdb

#### network structures
Encoder:
  which_network: DegModel
  setting:
    nf: 64
    nb: 8
    ksize: 21
    scale: 4
  pretrain: 
    path: ~
    strict_load: true

Decoder:
  which_network: EDSR
  setting:
    nf: 64
    nb: 16
    res_scale: 1
    upscale: 4
  pretrain: 
    path: ../../../checkpoints/EDSR/edsr_baseline_x4-new.pt
    strict_load: true

netD1:
  which_network: PatchGANDiscriminator
  setting:
    in_c: 3
    nf: 64
    nb: 5
    stride: 1
  pretrain: 
    path: ~
    strict_load: true

netD2:
  which_network: PatchGANDiscriminator
  setting:
    in_c: 3
    nf: 16
    nb: 5
    stride: 1
  pretrain: 
    path: ~
    strict_load: true

#### training settings: learning rate scheme, loss
train:
  resume_state: ~
  D_ratio: 5
  losses:
    sr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 0.0
    
    lr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 1.0

    sr_pix: 
      type: L1Loss
      weight: 10.0

  optimizers:
    Encoder:
      type: Adam
      lr: !!float 2e-4
    Decoder:
      type: Adam
      lr: !!float 2e-4
    netD1:
      type: Adam
      lr: !!float 2e-4
    netD2:
      type: Adam
      lr: !!float 2e-4
   
  niter: 200000
  warmup_iter: -1  # no warm up

  scheduler:
    type: MultiStepLR
    milestones: [100000]
    gamma: 0.5

  manual_seed: 0
  val_freq: !!float 5e2

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e2
