#### general settings
name: CycleGANSR
use_tb_logger: false
model: CycleGANModel
scale: 4
gpu_ids: [1]
metrics: [psnr, ssim]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: UnPairedDataset
    data_type: lmdb
    color: RGB
    ratios: [1, 4]

    dataroot_src: /mnt/raid/lzx/SRDatasets/NTIRE2020/track1/track1_train_source.lmdb
    dataroot_tgt: /mnt/raid/lzx/SRDatasets/NTIRE2020/train_target.lmdb

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 32
    tgt_size: 128
    src_size: 32
    use_flip: true
    use_rot: true

  val:
    name: 2020Track1_mini
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_src: /mnt/raid/lzx/SRDatasets/NTIRE2020/track1/valid_mini.lmdb
    dataroot_tgt: /mnt/raid/lzx/SRDatasets/DIV2K_valid/HR/x4_mini.lmdb

#### network structures  
netG1:
  which_network: EDSR
  setting:
    nf: 64
    nb: 16
    res_scale: 0.1
    upscale: 4
  pretrain: 
    path: ../../../checkpoints/EDSR/edsr_baseline_x4-6b446fab.pt
    strict_load: true

netD1:
  which_network: PatchGANDiscriminator
  setting:
    in_c: 3
    nf: 64
    nb: 3
  pretrain:
    path: ~
    strict_load: true

netG2:
  which_network: Translator
  setting:
    nf: 64
    nb: 8
    zero_tail: true
    scale: 0.25
  pretrain:
    path: ~
    strict_load: true

netD2:
  which_network: PatchGANDiscriminator
  setting:
    in_c: 3
    nf: 64
    nb: 3
  pretrain:
    path: ~
    strict_load: true

#### training settings: learning rate scheme, loss
train:
  resume_state: ~

  losses:
    g1d1_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 1.0

    g2d2_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 1.0
      
    g1_idt:
      type: L1Loss
      weight: 5.0
    
    g2_idt:
      type: L1Loss
      weight: 5.0

    g1g2_cycle:
      type: L1Loss
      weight: 10.0

    g2g1_cycle: 
      type: L1Loss
      weight: 10.0

  optimizers:
    netG1:
      type: Adam
      lr: !!float 2e-4
    netG2:
      type: Adam
      lr: !!float 2e-4
    netD1:
      type: Adam
      lr: !!float 2e-4
    netD2:
      type: Adam
      lr: !!float 2e-4
  
  niter: 100000
  warmup_iter: -1  # no warm up

  scheduler:
    type: MultiStepLR
    milestones: [50000]
    gamma: 0.5

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
