#### general settings
name: sr_bicubic_x2
use_tb_logger: false
model: SRModel
scale: 2
gpu_ids: [6]

metrics: [psnr, ssim]

datasets:
  test1:
    name: Set5
    mode: PairedDataset
    data_type: lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/Set5/BicLR/x2.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/Set5/HR/x2.lmdb
  test2:
    name: Set14
    mode: PairedDataset
    data_type: lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/Set14/BicLR/x2.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/Set14/HR/x2.lmdb
  test3:
    name: BSDS100
    mode: PairedDataset
    data_type: lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/BSDS100/BicLR/x2.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/BSDS100/HR/x2.lmdb
  test4:
    name: urban100
    mode: PairedDataset
    data_type: lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/urban100/BicLR/x2.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/urban100/HR/x2.lmdb
  test5:
    name: manga109
    mode: PairedDataset
    data_type: lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/manga109/BicLR/x2.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/manga109/HR/x2.lmdb
  test6:
    name: div2k
    mode: PairedDataset
    data_type: lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/DIV2K_valid/BicLR/x2.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/DIV2K_valid/HR/x2.lmdb

#### network structures
netSR:
  which_network: EDSR
  setting:
    nf: 64
    nb: 16
    res_scale: 0.1
    upscale: 2
  pretrain: 
    path: ../../../checkpoints/EDSR/edsr_baseline_x2-1bc95232.pt
    strict_load: true
