#### general settings
name: sr_debug
use_tb_logger: false
model: SRModel
scale: 4
gpu_ids: [2]
metrics: [psnr, ssim]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_tgt: /mnt/raid/lzx/SRDatasets/NTIRE2018/train_HR_half.lmdb
    dataroot_src: /mnt/raid/lzx/SRDatasets/DIV2K_train/BicLRx4_half.lmdb

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 32
    tgt_size: 128
    src_size: 32
    use_flip: true
    use_rot: true

  val:
    name: Set5
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_src: /mnt/raid/lzx/SRDatasets/Set5/BicLR/x4.lmdb
    dataroot_tgt: /mnt/raid/lzx/SRDatasets/Set5/HR/x4.lmdb

#### network structures
netSR:
  which_network: EDSR
  setting:
    nf: 64
    nb: 16
    res_scale: 0.1
    upscale: 4
  pretrain: 
    path: ../../../checkpoints/EDSR/edsr_baseline_x4-6b446fab.pt
    strict_load: true

#### training settings: learning rate scheme, loss
train:
  resume_state: ~

  losses:
    sr_pix: 
      type: L1Loss
      weight: 1.0

  optimizers:
    netSR:
      type: Adam
      lr: !!float 2e-4
    netD:
   
  niter: 400000
  warmup_iter: -1  # no warm up

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 5e3
