#### general settings
name: cyclegan_translation
use_tb_logger: false
model: CycleGANModel
scale: 4
gpu_ids: [1]
metrics: [psnr, ssim]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: PairedDataset
    data_type: lmdb
    color: RGB
    ratio: 8

    dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2020/BicLR_x4_half.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2017/trainx4_half.lmdb

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 64
    tgt_size: 32
    src_size: 32
    use_flip: true
    use_rot: true

  val:
    name: DIV2K
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_src: /mnt/hdd/lzx/SRDatasets/DIV2K_valid/Bic/x4.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/NTIRE2017/validx4.lmdb

#### network structures  
netG1:
  which_network: EDSR
  setting:
    nf: 64
    nb: 16
    res_scale: 1
    upscale: 1
  pretrain: 
    path: ~
    strict_load: true

netD1:
  which_network: DiscriminatorVGG32
  setting:
    in_nc: 3
    nf: 64

netG2:
  which_network: EDSR
  setting:
    nf: 64
    nb: 16
    res_scale: 1
    upscale: 1
  pretrain: 
    path: ~
    strict_load: true

netD2:
  which_network: DiscriminatorVGG32
  setting:
    in_nc: 3
    nf: 64

#### training settings: learning rate scheme, loss
train:
  resume_state: ~

  losses:
    g1_d1_adv:
      type: GANLoss
      gan_type: vanilla
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 1e-2

    g2_d2_adv:
      type: GANLoss
      gan_type: vanilla
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 1e-2

    g1g2_cycle:
      type: L1Loss
      weight: 1.0

    g2g1_cycle: 
      type: L1Loss
      weight: 1.0

  optimizers:
    netG1:
      type: Adam
      lr: !!float 2e-4
    netG2:
      type: Adam
      lr: !!float 2e-4
    netD1:
      type: Adam
      lr: !!float 2e-4
    netD2:
      type: Adam
      lr: !!float 2e-4
  
  niter: 400000
  warmup_iter: -1  # no warm up

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
