#### general settings
name: BSRGANTest
use_tb_logger: false
model: LatenTransModel
scale: 4
gpu_ids: [5]
metrics: [niqe, piqe]

#### datasets
datasets:
  train:
    name: BSRGAN
    mode: FixedImageDataset
    data_type: lmdb
    color: RGB

    dataroot_tgt: /home/lzx/SRDatasets/DIV2K_train/HR/x4.lmdb
    dataroot_src: /home/lzx/SRDatasets/BSRGANTest/RealSRSet/frog.png

    use_shuffle: true
    workers_per_gpu: 4  # per GPU
    imgs_per_gpu: 12
    tgt_size: 256
    src_size: 64
    use_flip: true
    use_rot: true

#### network structures
networks:
  Encoder:
    which_network: DegModel
    setting:
      scale: 4
      nc_img: 3
      kernel_opt: 
        mix: false
        spatial: false
        nc: 64
        nf: 64
        nb: 16
        head_k: 1
        body_k: 1
        ksize: 11
        zero_init: true
      noise_opt: 
        mix: true
        nc: 3
        nf: 64
        nb: 16
        head_k: 3
        body_k: 3
        dim: 3
        zero_init: true
    pretrain: 
      path: ~
      strict_load: true

  Decoder:
    which_network: EDSR
    setting:
      nf: 64
      nb: 16
      res_scale: 1
      upscale: 4
    pretrain: 
      path: ../../../checkpoints/EDSR/edsr_baseline_x4-new.pt
      strict_load: true
    
  netD1:
    which_network: PatchGANDiscriminator
    setting:
      in_c: 3
      nf: 64
      nb: 3
      stride: 1
    pretrain: 
      path: ~
      strict_load: true
  
  netD2:
    which_network: PatchGANDiscriminator
    setting:
      in_c: 3
      nf: 64
      nb: 3
      stride: 2
    pretrain: 
      path: ~
      strict_load: true

#### training settings: learning rate scheme, loss
train:
  resume_state: ~
  D_ratio: 1
  max_grad_norm: 50
  buffer_size: 0
  
  losses:
    sr_adv:
      type: GANLoss
      gan_type: vanilla
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 0.1
    
    lr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 1
    
    sr_percep:
      type: PerceptualLossLPIPS
      net: alex
      normalize: true
      weight: !!float 1.0
    
    noise_mean:
      type: MSELoss
      weight: 100
   
    sr_pix_trans: 
      type: MSELoss
      weight: 0.0
    
    sr_pix_sr: 
      type: L1Loss
      weight: 1.0
    
  optimizers:
    Encoder:
      type: Adam
      lr: !!float 1e-4
    Decoder:
      type: Adam
      lr: !!float 1e-4
    netD1:
      type: Adam
      lr: !!float 1e-4
    netD2:
      type: Adam
      lr: !!float 1e-4
   
  niter: 5000
  warmup_iter: -1  # no warm up

  decay_lr_prop: 0.99

  manual_seed: 0
  val_freq: !!float 5e2

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e2
