#### general settings
name: 2020Track1
use_tb_logger: false
model: LatenTransModel
scale: 4
gpu_ids: [1]
metrics: [psnr, ssim, lpips]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: UnPairedDataset
    data_type: lmdb
    color: RGB
    ratios: [1, 4]

    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/DIV2K_train/HR/x4.lmdb
    dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2020/track1/train_source.lmdb

    use_shuffle: true
    workers_per_gpu: 4  # per GPU
    imgs_per_gpu: 32
    tgt_size: 128
    src_size: 32
    use_flip: true
    use_rot: true

  val:
    name: 2020Track1
    mode: PairedDataset
    data_type: lmdb
    color: RGB

    dataroot_src: /mnt/hdd/lzx/SRDatasets/NTIRE2020/track1/valid_mini.lmdb
    dataroot_tgt: /mnt/hdd/lzx/SRDatasets/DIV2K_valid/HR/x4_mini.lmdb

#### network structures
networks:
  Encoder:
    which_network: DegModel
    setting:
      scale: 4
      kernel: true
      nc_k: 64
      nf_k: 64
      nb_k: 4
      ksize: 11
      noise: true
      nc_n: 3
      nf_n: 64
      nb_n: 4
    pretrain: 
      path: ~
      strict_load: true

  Decoder:
    which_network: EDSR
    setting:
      nf: 64
      nb: 16
      res_scale: 1
      upscale: 4
    pretrain: 
      path: ../../../checkpoints/EDSR/edsr_baseline_x4-new.pt
      strict_load: true

  netD1:
    which_network: PatchGANDiscriminator
    setting:
      in_c: 3
      nf: 64
      nb: 3
      stride: 1
    pretrain: 
      path: ~
      strict_load: true
  
  # netD2:
  #   which_network: PatchGANDiscriminator
  #   setting:
  #     in_c: 3
  #     nf: 64
  #     nb: 3
  #     stride: 1
  #   pretrain: 
  #     path: ~
  #     strict_load: true

#### training settings: learning rate scheme, loss
train:
  resume_state: ~
  D_ratio: 1
  max_grad_norm: 50
  buffer_size: 0
  
  losses:
    sr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 0.0
    
    lr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 1.0
    
    lr_quant:
      type: L1Loss
      weight: 1.0

    sr_pix_trans: 
      type: L1Loss
      weight: 10
    
    sr_pix_sr: 
      type: L1Loss
      weight: 1.0
    
    # lr_gauss:
    #   type: GaussGuided
    #   ksize: 31
    #   sigma: 4
    #   weight: 1

  optimizers:
    Encoder:
      type: Adam
      lr: !!float 2e-4
    Decoder:
      type: Adam
      lr: !!float 2e-4
    netD1:
      type: Adam
      lr: !!float 2e-4
    # netD2:
    #   type: Adam
    #   lr: !!float 2e-4
   
  niter: 200000
  warmup_iter: -1  # no warm up

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 150000]
    gamma: 0.5

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  
